-- Phase 9: Add remaining PolicyRuleType enum values for org-type-specific templates
ALTER TYPE "PolicyRuleType" ADD VALUE IF NOT EXISTS 'ESCROW_FUNDING';
ALTER TYPE "PolicyRuleType" ADD VALUE IF NOT EXISTS 'SUPPLIER_ACCEPTANCE';
ALTER TYPE "PolicyRuleType" ADD VALUE IF NOT EXISTS 'SETTLEMENT';
ALTER TYPE "PolicyRuleType" ADD VALUE IF NOT EXISTS 'EARLY_PAYMENT';
ALTER TYPE "PolicyRuleType" ADD VALUE IF NOT EXISTS 'LP_FUNDING';
ALTER TYPE "PolicyRuleType" ADD VALUE IF NOT EXISTS 'DISPUTE_RESOLUTION';
ALTER TYPE "PolicyRuleType" ADD VALUE IF NOT EXISTS 'DELIVERY_VERIFICATION';
